# Project Name
TARGET = PatchPulse

# Sources
CPP_SOURCES = PatchPulse.cpp

# Library Locations
LIBDAISY_DIR = ./vendor/libdaisy
DAISYSP_DIR = ./vendor/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

CFLAGS += -I/usr/local/include
LDFLAGS += -L/usr/local/lib


